pipeline{
    agent any

    stages{
        stage ('Build Stage'){
            steps{
                echo 'Building the code'
                 withMaven(maven: '3.8.6'){
                       bat 'mvn clean compile'
                   }
            }
        }
        stage ('Testing Stage'){
            steps{
                echo 'Testing the code'
                withMaven(maven: '3.8.6'){
                       bat 'mvn test'
                   }
            }
          }
        stage ('Deploy Stage'){
            steps{
                echo 'Deploying the code'
                withMaven(maven: '3.8.6'){
                        bat 'mvn deploy'
                   }
            }
            }
    }
}